# Generated by Django 5.2 on 2025-04-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='competition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='season',
            field=models.CharField(max_length=20),
        ),
    ]
