# Generated by Django 5.2 on 2025-04-16 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_calendar', '0003_alter_match_options_alter_match_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='match',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchday',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='season',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matches_calendar.league'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='competition',
        ),
    ]
