# Generated by Django 5.2 on 2025-04-16 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_calendar', '0004_league_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='league',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='matches_calendar.league'),
        ),
    ]
