# Generated by Django 5.2 on 2025-04-16 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_calendar', '0005_alter_match_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matches_calendar.league'),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
