# Generated by Django 5.2 on 2025-04-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches_calendar', '0007_alter_match_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='country',
        ),
    ]
