# Generated by Django 5.2 on 2025-04-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_calendar', '0009_alter_match_matchday'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['date'], name='matches_cal_date_58102d_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['league'], name='matches_cal_league__35d226_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['home_team'], name='matches_cal_home_te_998675_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['away_team'], name='matches_cal_away_te_3d886e_idx'),
        ),
    ]
