name: Update Matches Nightly

on:
  schedule:
    - cron: '0 23 * * *'  # ogni sera alle 23:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo

      - name: Set MONGO_URI secret as environment variable
        run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

      - name: Run MongoDB update script
        run: python matches_calendar/management/commands/update_matches.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
